name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 */6 * *'
    
jobs:
  Sync:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: full
               
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install -y p7zip p7zip-full p7zip-rar unrar
        pip install pycryptodome
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiemi --type rclone
        sudo -v ; curl https://rclone.org/install.sh | sudo bash
        
    # https://docs.github.com/zh/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-a-log
    - name: Ban
      run: |
        ${{ secrets.BAN }}

    - name: Sync helper
      continue-on-error: true
      run: |
        rclone --config=rclone.conf sync "Helper:" "BackupHelper:" --log-level INFO

    # - name: Sync Save
    #   run: |
    #     rclone --config=rclone.conf sync "Save:" "BackupSave:" --log-level INFO

    - name: Clean
      run: |
        python C.py --public "${{ secrets.PUBLIC }}" --private "${{ secrets.PRIVATE }}" --mode jiami --type rclone

    - name: Push
      run: |
        git init
        git config user.name Rcrwrate
        git config user.email 46920034+Rcrwrate@users.noreply.github.com
        git add .
        git commit -m "Sync update ${{ github.run_id }}"
        git filter-branch --force --index-filter 'if [ "$GIT_COMMIT" != "$(git rev-parse HEAD)" ]; then git rm --cached --ignore-unmatch rclone.conf; fi' --prune-empty --tag-name-filter cat -- --all
        git push origin --force --all
